---
- hosts: servers
  remote_user: root
  become: yes
  tasks:
  - name: Install java jdk
    apt: update_cache=true name=openjdk-8-jdk state=present
  - name: check java jdk version
    command: java -version
  - name: Install java 8 jre
    apt: name=openjdk-8-jre state=latest
  - name: Set Env of java
    command: echo "JAVA_HOME=$(which java)" | sudo tee -a /etc/environment
  - name: Verify the variable was set correctly
    command: echo $JAVA_HOME
  - name: Install Tomcat Apache
    apt: name=tomcat8 state=latest
