---
- hosts: servers 
  remote_user: root
  become: yes
  tasks:
  - name: Install java 8
    apt: name=openjdk-8-jdk state=present
  - name: check java version Install
    command: java -version
    become_user: '{{ global_vars.user_session }}'
    register: java_result
    ignore_errors: True
  - debug: 
      msg: "Failed - Java is not installed"
    when: java_result is failed
  - debug: 
      msg: "Success - Java is installed"
    when: java_result is success
